### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by phip1611** [MaderNoob/galloc#15]
Hi guys, I just want to let you know that this project seems pretty interesting.

I've seen that you benchmarked your allocator against my <https://crates.io/crates/simple-chunk-allocator> project - very cool!

The performance numbers are pretty impressive. I do not know much about allocators, but also didn't expect that one can outperform `chunk-allocator` or `linked-list-allocator` that much. I understand that `chunk-allocator` is not perfect as my goal with it was to have a "reasonable good" result with relative simple code.

Furthermore, I'd love to have a high-level description in two-four sentences why your solution is that much better than the `linked-list-allocator`'s strategy - while still being correct. Can you provide it and maybe add it to the readme?

~PS: Did you announce your project in the <https://rust-osdev.com/> newsletter?~
Nevermind, found it

**Comment by MaderNoob** [comment]
First of all we appreciate your interest in our project, we have put a lot of thought into it, and into making it good.

Basically our allocator provides mostly `O(1)` allocation and deallocation, because it uses two-level bins to store chunks of different sizes and alignments. This basically means that for every size under for example `64` bytes, and for every alignment under for example `1024`, the allocator stores a pointer to a linked list, in which all chunks are of that size and alignment, that way it can find chunks of some size and alignment in `O(1)`. There are many more performance optimizations at place in order to actually make it fast, you are welcome to dig into the code and see all the logic there.

If you have any more questions, feel free to ask.
